name: Pipeline Java Check, Build and Deploy on Docker CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: maven
      - name: Maven Build
        run: mvn package
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Deploy DockerHub
        uses: docker/build-push-action@v4
        with:
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_password}}
          repository: piero01/val_backend
          tags: latest
