name: Pipeline Java Check, Build and Deploy on Docker CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: maven
      - name: Maven Build
        run: mvn package
      - name: Log in Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Build Image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/val_backend_java
      - name: Push to DockerHub
        run: docker push ${{secrets.DOCKER_USERNAME}}/val_backend
